import { project_financial } from "@repo/types";

import { Pagination } from "../../../@types";

export const placeholder: Pagination<project_financial> = {
  data: [
    {
      id: "1",
      company_id: "1",
      work_type_id: "1",
      currency: "BRL",
      cycles: 1,
      title: "1",
      total_value: 1,
      discount: 1,
      project_version_id: "1",
      project_id: "1",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "2",
      company_id: "2",
      work_type_id: "2",
      currency: "BRL",
      cycles: 2,
      title: "1",
      total_value: 2,
      discount: 2,
      project_version_id: "2",
      project_id: "2",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "3",
      company_id: "3",
      work_type_id: "3",
      currency: "BRL",
      cycles: 3,
      title: "1",
      total_value: 3,
      discount: 3,
      project_version_id: "3",
      project_id: "3",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "4",
      company_id: "4",
      work_type_id: "4",
      currency: "BRL",
      cycles: 4,
      title: "1",
      total_value: 4,
      discount: 4,
      project_id: "4",
      project_version_id: "4",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "5",
      company_id: "5",
      work_type_id: "5",
      currency: "BRL",
      cycles: 5,
      title: "1",
      total_value: 5,
      discount: 5,
      project_version_id: "5",
      project_id: "5",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
  ],
  page: 1,
  pages: 1,
  count: 0,
};
