/**
 * Personal dashboard placeholder data
 * Used for initial data loading and skeleton states
 */

const now = new Date();
const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
const sixtyDaysAgo = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);
const twoYearsAgo = new Date(now.getTime() - 730 * 24 * 60 * 60 * 1000);

export const personalDashboardPlaceholder: any = {
  profile: {
    id: "1",
    userId: "user-1",
    userName: "João Silva",
    userEmail: "joao.silva@example.com",
    userAvatar: null,
    level: "Senior",
    companyName: "Intelipro",
  },
  profileInfo: {
    companyEntryDate: twoYearsAgo.toISOString(),
    timeInCompany: {
      years: 2,
      months: 3,
      days: 15,
      totalDays: 800,
    },
    profileCreatedAt: twoYearsAgo.toISOString(),
    profileUpdatedAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  summary: {
    totalProjects: 8,
    activeProjects: 5,
    completedProjects: 3,
    totalAllocations: 12,
    activeAllocations: 7,
    totalHoursWorked: 1240,
    totalHoursAllocated: 1600,
    totalCards: 45,
    pendingCards: 12,
    completedCards: 28,
    totalComments: 156,
    unreadCards: 5,
  },
  financial: {
    proportional: {
      totalCompensation: 44000,
      baseSalary: 40000,
      totalBonuses: 4000,
    },
    integral: {
      totalCompensation: 52800,
      baseSalary: 48000,
      totalBonuses: 4800,
    },
    roles: [
      {
        roleId: "1",
        roleName: "Desenvolvedor Sênior",
        costCenterName: "Desenvolvimento",
        salary_proportional: 40000,
        salary_integral: 48000,
        currency: "BRL",
      },
      {
        roleId: "2",
        roleName: "Desenvolvedor Sênior",
        costCenterName: "Desenvolvimento",
        salary_proportional: 40000,
        salary_integral: 48000,
        currency: "BRL",
      },
    ],
    bonuses: [
      {
        bonusId: "1",
        bonusName: "Bônus de Performance",
        costCenterName: "Desenvolvimento",
        amount_proportional: 2500,
        amount_integral: 3000,
        currency: "BRL",
      },
      {
        bonusId: "2",
        bonusName: "Bônus de Projeto",
        costCenterName: "Desenvolvimento",
        amount_proportional: 1500,
        amount_integral: 1800,
        currency: "BRL",
      },
    ],
    currency: "BRL",
  },
  financialEvolution: {
    data: [
      {
        date: new Date(now.getTime() - 11 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Janeiro",
        year: 2023,
        totalSalary: 40000,
        totalBonuses: 2000,
        totalCompensation: 42000,
        currency: "BRL",
        roles: [{ roleId: "1", roleName: "Desenvolvedor Pleno", amount: 40000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 2000 }],
      },
      {
        date: new Date(now.getTime() - 10 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Fevereiro",
        year: 2023,
        totalSalary: 40000,
        totalBonuses: 1500,
        totalCompensation: 41500,
        currency: "BRL",
        roles: [{ roleId: "1", roleName: "Desenvolvedor Pleno", amount: 40000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 1500 }],
      },
      {
        date: new Date(now.getTime() - 9 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Março",
        year: 2023,
        totalSalary: 42000,
        totalBonuses: 2500,
        totalCompensation: 44500,
        currency: "BRL",
        roles: [{ roleId: "1", roleName: "Desenvolvedor Pleno", amount: 42000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 2500 }],
      },
      {
        date: new Date(now.getTime() - 8 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Abril",
        year: 2023,
        totalSalary: 42000,
        totalBonuses: 2000,
        totalCompensation: 44000,
        currency: "BRL",
        roles: [{ roleId: "1", roleName: "Desenvolvedor Pleno", amount: 42000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 2000 }],
      },
      {
        date: new Date(now.getTime() - 7 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Maio",
        year: 2023,
        totalSalary: 45000,
        totalBonuses: 3000,
        totalCompensation: 48000,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 45000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 3000 }],
      },
      {
        date: new Date(now.getTime() - 6 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Junho",
        year: 2023,
        totalSalary: 45000,
        totalBonuses: 2500,
        totalCompensation: 47500,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 45000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 2500 }],
      },
      {
        date: new Date(now.getTime() - 5 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Julho",
        year: 2023,
        totalSalary: 47000,
        totalBonuses: 3500,
        totalCompensation: 50500,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 47000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 3500 }],
      },
      {
        date: new Date(now.getTime() - 4 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Agosto",
        year: 2023,
        totalSalary: 47000,
        totalBonuses: 2800,
        totalCompensation: 49800,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 47000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 2800 }],
      },
      {
        date: new Date(now.getTime() - 3 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Setembro",
        year: 2023,
        totalSalary: 48000,
        totalBonuses: 4000,
        totalCompensation: 52000,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 48000 }],
        bonuses: [
          { bonusId: "1", bonusName: "Bônus de Performance", amount: 3000 },
          { bonusId: "2", bonusName: "Bônus de Projeto", amount: 1000 },
        ],
      },
      {
        date: new Date(now.getTime() - 2 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Outubro",
        year: 2023,
        totalSalary: 48000,
        totalBonuses: 3500,
        totalCompensation: 51500,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 48000 }],
        bonuses: [{ bonusId: "1", bonusName: "Bônus de Performance", amount: 3500 }],
      },
      {
        date: new Date(now.getTime() - 1 * 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        month: "Novembro",
        year: 2023,
        totalSalary: 48000,
        totalBonuses: 4200,
        totalCompensation: 52200,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 48000 }],
        bonuses: [
          { bonusId: "1", bonusName: "Bônus de Performance", amount: 3000 },
          { bonusId: "2", bonusName: "Bônus de Projeto", amount: 1200 },
        ],
      },
      {
        date: now.toISOString().split("T")[0],
        month: "Dezembro",
        year: 2023,
        totalSalary: 48000,
        totalBonuses: 4800,
        totalCompensation: 52800,
        currency: "BRL",
        roles: [{ roleId: "2", roleName: "Desenvolvedor Sênior", amount: 48000 }],
        bonuses: [
          { bonusId: "1", bonusName: "Bônus de Performance", amount: 3000 },
          { bonusId: "2", bonusName: "Bônus de Projeto", amount: 1800 },
        ],
      },
    ],
    currency: "BRL",
    totalPeriods: 12,
    averageSalary: 45000,
    averageBonuses: 2900,
    averageCompensation: 47900,
    highestCompensation: 52800,
    lowestCompensation: 41500,
  },
  projects: [
    {
      projectId: "1",
      projectName: "Sistema de Gestão Empresarial",
      versionName: "v2.1.0",
      role: "Desenvolvedor Sênior",
      status: "active",
      startDate: sixtyDaysAgo,
      endDate: null,
      allocatedHours: 320,
      workedHours: 280,
      progress: 87.5,
    },
    {
      projectId: "2",
      projectName: "Plataforma E-commerce",
      versionName: "v1.5.2",
      role: "Desenvolvedor Sênior",
      status: "active",
      startDate: new Date(now.getTime() - 195 * 24 * 60 * 60 * 1000),
      endDate: null,
      allocatedHours: 400,
      workedHours: 380,
      progress: 95,
    },
    {
      projectId: "3",
      projectName: "Aplicativo Mobile",
      versionName: "v1.0.0",
      role: "Tech Lead",
      status: "active",
      startDate: new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000),
      endDate: null,
      allocatedHours: 240,
      workedHours: 200,
      progress: 83.33,
    },
    {
      projectId: "4",
      projectName: "Sistema de BI e Analytics",
      versionName: "v1.2.0",
      role: "Desenvolvedor Sênior",
      status: "active",
      startDate: thirtyDaysAgo,
      endDate: null,
      allocatedHours: 280,
      workedHours: 180,
      progress: 64.29,
    },
    {
      projectId: "5",
      projectName: "Portal do Cliente",
      versionName: "v2.0.0",
      role: "Desenvolvedor Sênior",
      status: "active",
      startDate: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
      endDate: null,
      allocatedHours: 200,
      workedHours: 40,
      progress: 20,
    },
    {
      projectId: "6",
      projectName: "Integração ERP",
      versionName: "v1.1.0",
      role: "Desenvolvedor Sênior",
      status: "completed",
      startDate: new Date(now.getTime() - 70 * 24 * 60 * 60 * 1000),
      endDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
      allocatedHours: 160,
      workedHours: 160,
      progress: 100,
    },
  ],
  metadata: {
    generatedAt: now.toISOString(),
    dateRange: {
      start: sixtyDaysAgo.toISOString().split("T")[0],
      end: now.toISOString().split("T")[0],
    },
  },
  currencyMetadata: {
    availableCurrencies: ["BRL", "USD", "EUR"],
    conversionApplied: false,
    targetCurrency: "BRL",
  },
};
