import { client_bank_account } from "@repo/api/generator/types";

import { Pagination } from "@/types/pagination";

export const placeholder: Pagination<client_bank_account> = {
  data: [
    {
      id: "1",
      client_id: "1",
      company_id: "1",
      account: "1",
      digit: "1",
      bank_number: "1",
      type: "1",
      principal: true,
      comment: "1",
      bank_name: "1",
      agency: "1",
      country: "1",
      deleted: false,
      deletedAt: null,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: "2",
      client_id: "2",
      company_id: "2",
      account: "2",
      digit: "2",
      bank_number: "2",
      type: "2",
      principal: true,
      comment: "2",
      bank_name: "2",
      agency: "2",
      country: "2",
      deleted: false,
      deletedAt: null,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: "3",
      client_id: "3",
      company_id: "3",
      account: "3",
      digit: "3",
      bank_number: "3",
      type: "3",
      principal: true,
      comment: "3",
      bank_name: "3",
      agency: "3",
      country: "3",
      deleted: false,
      deletedAt: null,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  ],
  page: 1,
  pages: 1,
  count: 0,
};
