import { project_kanban_cycle_card_type } from "@repo/types";

import { Pagination } from "../../../@types";

export const placeholder: Pagination<project_kanban_cycle_card_type> = {
  data: [
    {
      id: "1",
      title: "Backlog",
      icon: "backlog",
      color: "#3B82F6",
      principal: true,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      problem: false,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "2",
      title: "To Do",
      icon: "todo",
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      problem: false,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "3",
      title: "In Progress",
      icon: "inprogress",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "4",
      title: "Done",
      icon: "done",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "5",
      title: "Review",
      icon: "review",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "6",
      title: "Done",
      icon: "done",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "7",
      title: "Review",
      icon: "review",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "8",
      title: "Done",
      icon: "done",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "9",
      title: "Done",
      icon: "done",
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      problem: false,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
    {
      id: "10",
      title: "Done",
      icon: "done",
      problem: false,
      color: "#F59E0B",
      principal: false,
      deleted: false,
      project_kanban_cycle_id: "1",
      company_id: "1",
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      deletedAt: null,
      project_kanban_id: "1",
      project_id: "1",
      kanban_template_card_type_id: "1",
    },
  ],
  page: 1,
  pages: 1,
  count: 0,
};
