packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19.2.0"
  react-dom: "^19.2.0"
  next: "^15.5.7"
  next-intl: "^4.5.5"
  next-themes: "^0.4.6"
  "@tanstack/react-query": "^5.90.10"
  react-hook-form: "^7.66.1"
  zod: "^3.25.76"
  date-fns: "^4.1.0"
  lucide-react: "^0.562.0"
  sonner: "^2.0.7"
  recharts: "^2.15.3"
  "@types/react": "^19.2.6"
  "@types/react-dom": "^19.2.3"
  eslint: "^9.39.1"
  typescript: "5.9.3"
  "eslint-config-next": "^15.5.6"
  "@reduxjs/toolkit": "^2.5.0"
  "@tanstack/react-query-devtools": "^5.90.10"
  "@types/node": "^24.10.1"
  "axios": "^1.13.2"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "cookies-next": "^5.1.0"
  "eslint-plugin-turbo": "^2.7.4"
  "prettier": "^3.6.2"
  "prettier-plugin-tailwindcss": "^0.6.14"
  "react-redux": "^9.2.0"
  "redux": "^5.0.1"
  "redux-persist": "^6.0.0"
  "redux-saga": "^1.4.2"
  "tailwind-merge": "^3.4.0"
  "tailwindcss": "^4.1.17"
  "tailwindcss-animate": "^1.0.7"
  "turbo": "^2.7.4"

  
