packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19.2.0"
  react-dom: "^19.2.0"
  next: "^15.5.6"
  next-intl: "^4.5.5"
  next-themes: "^0.4.6"
  "@tanstack/react-query": "^5.90.10"
  react-hook-form: "^7.66.1"
  zod: "^3.25.76"
  date-fns: "^4.1.0"
  lucide-react: "^0.562.0"
  sonner: "^2.0.7"
  recharts: "^2.15.3"
