/**
 * Subscription placeholder data
 * Used for initial data loading and skeleton states
 */
import type { subscription } from "@repo/types";

import type { Pagination } from "../../../../core/domain/entities/pagination.entity";

export const subscriptionPlaceholder: Pagination<subscription> = {
  data: [
    {
      id: "sub_placeholder_1",
      deleted: false,
      deletedAt: null,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      company_id: "company_placeholder_1",
      plan_id: "plan_placeholder_1",
      model: "standard",
      gateway_subscription_id: "gw_sub_123",
      cancel_at_period_end: false,
      canceled_at: null,
      days_off: 0,
      start_date: new Date().toISOString(),
      end_date: null,
      status: "active",
      gateway: "manual",
      is_test: false,
      cancel_in: null,
      cancel_effective_at: null,
      company: {
        id: "company_placeholder_1",
        deleted: false,
        deletedAt: null,
        language: "pt-BR",
        logo_original_name: null,
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        name: "Empresa Exemplo",
        logo: null,
        email: "empresa@exemplo.com",
        phone: "+55 11 99999-9999",
        in_config: true,
        custom: false,
        entity: "LTDA",
        type: "Tecnologia",
        creator_id: "user_creator_1",
        creator: {
          id: "user_creator_1",
          deleted: false,
          deletedAt: null,
          avatar_original_name: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          name: "João da Silva",
          avatar: null,
          provider: "email",
          email: "joao@empresa.com",
          active: true,
          password: null,
          password_confirm: null,
          need_reset: false,
          confirmed: true,
          default_profile_id: "profile_1",
          confirmed_date: new Date().toISOString(),
          recovery_code: null,
          recovery_date: null,
          confirm_code: null,
          confirm_date: null,
        },
        billing_errors: [],
        chats: [
          {
            id: "chat_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            profile_id: "profile_1",
            features: "Suporte",
            title: "Chat de Suporte",
          },
        ],
        company_address: {
          id: "address_1",
          deleted: false,
          deletedAt: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          street: "Rua Exemplo",
          complement: "Sala 101",
          city: "São Paulo",
          state: "SP",
          country: "Brasil",
          zip_code: "01000-000",
          company_id: "company_placeholder_1",
          number: "100",
          neighborhood: "Centro",
        },
        company_contacts: [
          {
            id: "contact_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            type: "comercial",
            register: "11999999999",
          },
        ],
        company_customer: {
          id: "customer_1",
          deleted: false,
          deletedAt: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          company_id: "company_placeholder_1",
          customer_id: "customer_1",
        },
        company_documents: [
          {
            id: "doc_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            type: "CNPJ",
            register: "12.345.678/0001-99",
          },
        ],
        company_files: [
          {
            id: "file_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            file: "contrato.pdf",
            vector: false,
            vector_error: null,
            name: "Contrato",
          },
        ],
        company_invoices: [
          {
            id: "invoice_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            value: 99.9,
            success: true,
            last_digits: "1234",
            metadata: null,
            flag_card: "Visa",
            currency: "BRL",
            title: "Fatura Mensal",
            status: "paga",
            description: "Assinatura mensal",
            company: undefined,
          },
        ],
        invites: [],
        levels: [],
        modules: [],
        notifications: [],
        plans: [],
        profiles: [],
        subscriptions: [],
        subscription_changes: [],
        subscription_plans: [],
        logs: [],
      },
      plan: {
        id: "plan_placeholder_1",
        deleted: false,
        deletedAt: null,
        currency: "BRL",
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        title: "Plano Exemplo",
        price: 99.9,
        billing_model: "monthly",
        free_test: 7,
        licenses: 10,
        gateway: "manual",
        metadata: { description: "Plano para empresas de tecnologia", tags: ["premium", "mensal"] },
        price_id: "price_123",
        company_id: "company_placeholder_1",
        icon: "Award",
        is_popular: true,
        order: 1,
        company: undefined,
        plan_features: [],
        subscriptions: [],
        subscription_changes: [],
        subscription_changes_by_to_plan: [],
      },
      subscription_changes: [],
      subscription_plan: {
        id: "subplan_1",
        deleted: false,
        deletedAt: null,
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        subscription_id: "sub_placeholder_1",
        currency: "BRL",
        title: "Plano Exemplo",
        price: 99.9,
        billing_model: "monthly",
        free_test: 7,
        licenses: 10,
        gateway: "manual",
        company_id: "company_placeholder_1",
        icon: "Award",
        metadata: { description: "Plano de assinatura ativo", tags: ["ativo", "mensal"] },
        price_id: "price_123",
        subscription: undefined,
        company: undefined,
        subscription_plan_features: [],
      },
    },
  ],
  count: 1,
  page: 1,
  pages: 1,
};
