import { project_kanban_cycle } from '@/api/generator/types';

const cols = [null, 'backlog-1', 'todo-1', 'progress-1', 'review-1', 'done-1'];

export const placeholder: project_kanban_cycle = {
    id: '1',
    prepare: false,
    deleted: false,
    deletedAt: null,
    updatedAt: '',
    createdAt: '',
    title: 'Sprint 1 - Desenvolvimento',
    order: 1,
    work_type_id: '1',
    util_day: 1,
    project_version_id: '1',
    kanban_template_id: '1',
    project_kanban_id: '1',
    company_id: '1',
    start_date: '',
    end_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 dias no futuro
    project_id: '1',
    project_kanban_cycle_columns: [
        {
            id: '1',
            deleted: false,
            deletedAt: null,
            updatedAt: '',
            description: '',
            createdAt: '',
            title: 'Backlog',
            order: 1,
            project_kanban_cycle_id: '1',
            company_id: '1',
            color: 'transparent',
            limit: 20,
            finished: false,
            project_kanban_id: '1',
            project_id: '1',
            project_kanban_cycle_cards: Array.from({ length: 6 }, (_, index) => ({
                id: `backlog-${index + 1}`,
                deleted: false,
                public_id: index + 1,
                accept_description: null,
                work_type_id: '1',
                estimate: 1,
                estimate_unit: '1',
                execute: 1,
                execute_unit: '1',
                work_in_progress: 1,
                work_in_progress_unit: '1',
                priority: 1,
                severity: 1,
                end_date_estimate: '2021-01-01',
                end_date_execute: '2021-01-01',
                project_kanban_objective_id: '1',
                project_kanban_objective_target_id: '1',
                deletedAt: null,
                updatedAt: '',
                createdAt: '',
                project_member_id: '1',
                profile_id: '1',
                title: '',
                order: index + 1,
                description: `Descrição da tarefa de backlog ${index + 1}`,
                project_kanban_cycle_card_type_id: index === 0 ? '1' : '2',
                card_id: cols[index],
                project_kanban_cycle_column_id: '1',
                company_id: '1',
                project_kanban_cycle_id: '1',
                project_kanban_id: '1',
                project_id: '1'
            }))
        },
        {
            id: '2',
            deleted: false,
            deletedAt: null,
            updatedAt: '',
            createdAt: '',
            title: '',
            description: '',
            order: 2,
            project_kanban_cycle_id: '1',
            company_id: '1',
            color: 'transparent',
            limit: 15,
            finished: false,
            project_kanban_id: '1',
            project_id: '1',
            project_kanban_cycle_cards: Array.from({ length: 6 }, (_, index) => ({
                id: `todo-${index + 1}`,
                deleted: false,
                deletedAt: null,
                accept_description: null,
                updatedAt: '',
                createdAt: '',
                public_id: index + 1,
                work_type_id: '1',
                estimate: 1,
                estimate_unit: '1',
                execute: 1,
                execute_unit: '1',
                work_in_progress: 1,
                work_in_progress_unit: '1',
                priority: 1,
                severity: 1,
                end_date_estimate: '2021-01-01',
                end_date_execute: '2021-01-01',
                project_kanban_objective_id: '1',
                project_kanban_objective_target_id: '1',
                project_member_id: '1',
                profile_id: '1',
                title: '',
                order: index + 1,
                description: `Descrição da tarefa to do ${index + 1}`,
                project_kanban_cycle_card_type_id: index === 0 ? '1' : '2',
                card_id: cols[index],
                project_kanban_cycle_column_id: '1',
                company_id: '1',
                project_kanban_cycle_id: '1',
                project_kanban_id: '1',
                project_id: '1'
            }))
        },
        {
            id: '3',
            deleted: false,
            deletedAt: null,
            updatedAt: '',
            createdAt: '',
            title: 'In Progress',
            description: '',
            order: 3,
            project_kanban_cycle_id: '1',
            company_id: '1',
            color: 'transparent',
            limit: 10,
            finished: false,
            project_kanban_id: '1',
            project_id: '1',
            project_kanban_cycle_cards: Array.from({ length: 6 }, (_, index) => ({
                id: `progress-${index + 1}`,
                deleted: false,
                deletedAt: null,
                accept_description: null,
                updatedAt: '',
                createdAt: '',
                public_id: index + 1,
                work_type_id: '1',
                estimate: 1,
                estimate_unit: '1',
                execute: 1,
                execute_unit: '1',
                work_in_progress: 1,
                work_in_progress_unit: '1',
                priority: 1,
                severity: 1,
                end_date_estimate: '2021-01-01',
                end_date_execute: '2021-01-01',
                project_kanban_objective_id: '1',
                project_kanban_objective_target_id: '1',
                project_member_id: '1',
                profile_id: '1',
                title: '',
                order: index + 1,
                description: `Descrição da tarefa em progresso ${index + 1}`,
                project_kanban_cycle_card_type_id: index === 0 ? '1' : '2',
                card_id: cols[index],
                project_kanban_cycle_column_id: '1',
                company_id: '1',
                project_kanban_cycle_id: '1',
                project_kanban_id: '1',
                project_id: '1'
            }))
        },
        {
            id: '4',
            deleted: false,
            deletedAt: null,
            updatedAt: '',
            createdAt: '',
            title: 'Review',
            description: '',
            order: 4,
            project_kanban_cycle_id: '1',
            company_id: '1',
            color: 'transparent',
            limit: 8,
            finished: false,
            project_kanban_id: '1',
            project_id: '1',
            project_kanban_cycle_cards: Array.from({ length: 6 }, (_, index) => ({
                id: `review-${index + 1}`,
                deleted: false,
                deletedAt: null,
                accept_description: null,
                updatedAt: '',
                createdAt: '',
                public_id: index + 1,
                work_type_id: '1',
                estimate: 1,
                estimate_unit: '1',
                execute: 1,
                execute_unit: '1',
                work_in_progress: 1,
                work_in_progress_unit: '1',
                priority: 1,
                severity: 1,
                end_date_estimate: '2021-01-01',
                end_date_execute: '2021-01-01',
                project_kanban_objective_id: '1',
                project_kanban_objective_target_id: '1',
                project_member_id: '1',
                profile_id: '1',
                title: '',
                order: index + 1,
                description: `Descrição da tarefa em revisão ${index + 1}`,
                project_kanban_cycle_card_type_id: index === 0 ? '1' : '2',
                card_id: cols[index],
                project_kanban_cycle_column_id: '1',
                company_id: '1',
                project_kanban_cycle_id: '1',
                project_kanban_id: '1',
                project_id: '1'
            }))
        },
        {
            id: '5',
            deleted: false,
            deletedAt: null,
            updatedAt: '',
            createdAt: '',
            title: 'Done',
            description: '',
            order: 5,
            project_kanban_cycle_id: '1',
            company_id: '1',
            color: 'transparent',
            limit: 50,
            finished: true,
            project_kanban_id: '1',
            project_id: '1',
            project_kanban_cycle_cards: Array.from({ length: 6 }, (_, index) => ({
                id: `done-${index + 1}`,
                deleted: false,
                deletedAt: null,
                accept_description: null,
                updatedAt: '',
                createdAt: '',
                public_id: index + 1,
                work_type_id: '1',
                estimate: 1,
                estimate_unit: '1',
                execute: 1,
                execute_unit: '1',
                work_in_progress: 1,
                work_in_progress_unit: '1',
                priority: 1,
                severity: 1,
                end_date_estimate: '2021-01-01',
                end_date_execute: '2021-01-01',
                project_kanban_objective_id: '1',
                project_kanban_objective_target_id: '1',
                project_member_id: '1',
                profile_id: '1',
                title: '',
                order: index + 1,
                description: `Descrição da tarefa concluída ${index + 1}`,
                project_kanban_cycle_card_type_id: index === 0 ? '1' : '2',
                card_id: cols[index],
                project_kanban_cycle_column_id: '1',
                company_id: '1',
                project_kanban_cycle_id: '1',
                project_kanban_id: '1',
                project_id: '1'
            }))
        }
    ]
};
