import { project_tool } from "@repo/api/generator/types";

import { Pagination } from "@/types/pagination";

export const placeholder: Pagination<project_tool> = {
  data: [
    {
      id: "1",
      company_id: "1",
      currency: "BRL",
      value: 1,
      title: "1",
      description: "1",
      consumption: "daily",
      type: "1",
      recurrence: "monthly",
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
      project_version_id: "1",
      project_id: "1",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "2",
      company_id: "2",
      currency: "BRL",
      title: "1",
      description: "1",
      value: 2,
      recurrence: "monthly",
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
      consumption: "daily",
      type: "1",
      project_version_id: "2",
      project_id: "2",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "3",
      company_id: "3",
      currency: "BRL",
      title: "1",
      description: "1",
      value: 3,
      recurrence: "monthly",
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
      consumption: "daily",
      type: "1",
      project_version_id: "3",
      project_id: "3",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "4",
      company_id: "4",
      consumption: "daily",
      type: "1",
      title: "1",
      description: "1",
      value: 4,
      recurrence: "monthly",
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
      currency: "BRL",
      project_id: "4",
      project_version_id: "4",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
    {
      id: "5",
      company_id: "5",
      title: "1",
      description: "1",
      value: 5,
      consumption: "daily",
      type: "1",
      recurrence: "monthly",
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
      currency: "BRL",
      project_version_id: "5",
      project_id: "5",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
    },
  ],
  page: 1,
  pages: 1,
  count: 0,
};
