import { document, documentCreateInput } from "./document";
import { company_chunk, company_chunkCreateInput } from "./company_chunk";
import { user, userCreateInput } from "./user";
import { billing_error, billing_errorCreateInput } from "./billing_error";
import { chat, chatCreateInput } from "./chat";
import { client, clientCreateInput } from "./client";
import { client_address, client_addressCreateInput } from "./client_address";
import { client_bank_account, client_bank_accountCreateInput } from "./client_bank_account";
import { client_contact, client_contactCreateInput } from "./client_contact";
import { client_document, client_documentCreateInput } from "./client_document";
import { client_file, client_fileCreateInput } from "./client_file";
import { company_address, company_addressCreateInput } from "./company_address";
import { company_config, company_configCreateInput } from "./company_config";
import { company_contact, company_contactCreateInput } from "./company_contact";
import { company_customer, company_customerCreateInput } from "./company_customer";
import { company_document, company_documentCreateInput } from "./company_document";
import { company_file, company_fileCreateInput } from "./company_file";
import { company_invoice, company_invoiceCreateInput } from "./company_invoice";
import { cost_center, cost_centerCreateInput } from "./cost_center";
import { integration, integrationCreateInput } from "./integration";
import { invite, inviteCreateInput } from "./invite";
import { kanban_template, kanban_templateCreateInput } from "./kanban_template";
import { kanban_template_card, kanban_template_cardCreateInput } from "./kanban_template_card";
import { kanban_template_card_type, kanban_template_card_typeCreateInput } from "./kanban_template_card_type";
import { kanban_template_column, kanban_template_columnCreateInput } from "./kanban_template_column";
import { kanban_template_tag, kanban_template_tagCreateInput } from "./kanban_template_tag";
import { level, levelCreateInput } from "./level";
import { module, moduleCreateInput } from "./module";
import { notification, notificationCreateInput } from "./notification";
import { plan, planCreateInput } from "./plan";
import { profile, profileCreateInput } from "./profile";
import { profile_address, profile_addressCreateInput } from "./profile_address";
import { profile_bank_account, profile_bank_accountCreateInput } from "./profile_bank_account";
import { profile_bonus, profile_bonusCreateInput } from "./profile_bonus";
import { profile_contact, profile_contactCreateInput } from "./profile_contact";
import { profile_document, profile_documentCreateInput } from "./profile_document";
import { profile_file, profile_fileCreateInput } from "./profile_file";
import { profile_role, profile_roleCreateInput } from "./profile_role";
import { project, projectCreateInput } from "./project";
import { project_allocation, project_allocationCreateInput } from "./project_allocation";
import { project_config, project_configCreateInput } from "./project_config";
import { project_financial, project_financialCreateInput } from "./project_financial";
import { project_financial_employees, project_financial_employeesCreateInput } from "./project_financial_employees";
import { project_kanban, project_kanbanCreateInput } from "./project_kanban";
import { project_kanban_cycle, project_kanban_cycleCreateInput } from "./project_kanban_cycle";
import { project_kanban_cycle_allocation, project_kanban_cycle_allocationCreateInput } from "./project_kanban_cycle_allocation";
import { project_kanban_cycle_card, project_kanban_cycle_cardCreateInput } from "./project_kanban_cycle_card";
import { project_kanban_cycle_card_comment, project_kanban_cycle_card_commentCreateInput } from "./project_kanban_cycle_card_comment";
import { project_kanban_cycle_card_file, project_kanban_cycle_card_fileCreateInput } from "./project_kanban_cycle_card_file";
import { project_kanban_cycle_card_read, project_kanban_cycle_card_readCreateInput } from "./project_kanban_cycle_card_read";
import { project_kanban_cycle_card_tag, project_kanban_cycle_card_tagCreateInput } from "./project_kanban_cycle_card_tag";
import { project_kanban_cycle_card_type, project_kanban_cycle_card_typeCreateInput } from "./project_kanban_cycle_card_type";
import { project_kanban_cycle_column, project_kanban_cycle_columnCreateInput } from "./project_kanban_cycle_column";
import { project_kanban_objective, project_kanban_objectiveCreateInput } from "./project_kanban_objective";
import { project_kanban_objective_target, project_kanban_objective_targetCreateInput } from "./project_kanban_objective_target";
import { project_member, project_memberCreateInput } from "./project_member";
import { project_tool, project_toolCreateInput } from "./project_tool";
import { project_version, project_versionCreateInput } from "./project_version";
import { role, roleCreateInput } from "./role";
import { subscription, subscriptionCreateInput } from "./subscription";
import { subscription_changes, subscription_changesCreateInput } from "./subscription_changes";
import { subscription_plan, subscription_planCreateInput } from "./subscription_plan";
import { work_type, work_typeCreateInput } from "./work_type";
import { log__company, log__companyCreateInput } from "./log__company";

export interface company {
  language: string;
  documents?: document[];
  company_chunks?: company_chunk[];
  id: string;
  deleted: boolean;
  deletedAt: string | null;
  updatedAt: string;
  createdAt: string;
  name: string;
  logo: string | null;
  email: string;
  phone: string;
  in_config: boolean;
  custom: boolean;
  entity: string;
  type: string;
  creator_id: string;
  logo_original_name: string | null;
  creator?: user;
  billing_errors?: billing_error[];
  chats?: chat[];
  clients?: client[];
  client_address?: client_address[];
  client_bank_accounts?: client_bank_account[];
  client_contacts?: client_contact[];
  client_documents?: client_document[];
  client_files?: client_file[];
  company_address?: company_address;
  company_config?: company_config;
  company_contacts?: company_contact[];
  company_customer?: company_customer;
  company_documents?: company_document[];
  company_files?: company_file[];
  company_invoices?: company_invoice[];
  cost_centers?: cost_center[];
  integrations?: integration[];
  invites?: invite[];
  kanban_templates?: kanban_template[];
  kanban_template_cards?: kanban_template_card[];
  kanban_template_card_types?: kanban_template_card_type[];
  kanban_template_columns?: kanban_template_column[];
  kanban_template_tags?: kanban_template_tag[];
  levels?: level[];
  modules?: module[];
  notifications?: notification[];
  plans?: plan[];
  profiles?: profile[];
  profile_address?: profile_address[];
  profile_bank_accounts?: profile_bank_account[];
  profile_bonus?: profile_bonus[];
  profile_contacts?: profile_contact[];
  profile_documents?: profile_document[];
  profile_files?: profile_file[];
  profile_roles?: profile_role[];
  projects?: project[];
  project_allocations?: project_allocation[];
  project_configs?: project_config[];
  project_financials?: project_financial[];
  project_financial_employees?: project_financial_employees[];
  project_kanbans?: project_kanban[];
  project_kanban_cycles?: project_kanban_cycle[];
  project_kanban_cycle_allocations?: project_kanban_cycle_allocation[];
  project_kanban_cycle_cards?: project_kanban_cycle_card[];
  project_kanban_cycle_card_comments?: project_kanban_cycle_card_comment[];
  project_kanban_cycle_card_files?: project_kanban_cycle_card_file[];
  project_kanban_cycle_card_reads?: project_kanban_cycle_card_read[];
  project_kanban_cycle_card_tags?: project_kanban_cycle_card_tag[];
  project_kanban_cycle_card_types?: project_kanban_cycle_card_type[];
  project_kanban_cycle_columns?: project_kanban_cycle_column[];
  project_kanban_objectives?: project_kanban_objective[];
  project_kanban_objective_targets?: project_kanban_objective_target[];
  project_members?: project_member[];
  project_tools?: project_tool[];
  project_versions?: project_version[];
  roles?: role[];
  subscriptions?: subscription[];
  subscription_changes?: subscription_changes[];
  subscription_plans?: subscription_plan[];
  work_types?: work_type[];
  logs?: log__company[];
}

export interface companyCreateInput {
  language?: string;
  documents?: documentCreateInput[];
  company_chunks?: company_chunkCreateInput[];
  id?: string;
  deleted?: boolean;
  deletedAt?: string | null;
  updatedAt?: string;
  createdAt?: string;
  name: string;
  logo?: string | null;
  email: string;
  phone: string;
  in_config?: boolean;
  custom?: boolean;
  entity: string;
  type: string;
  creator_id?: string;
  logo_original_name?: string | null;
  creator?: userCreateInput;
  billing_errors?: billing_errorCreateInput[];
  chats?: chatCreateInput[];
  clients?: clientCreateInput[];
  client_address?: client_addressCreateInput[];
  client_bank_accounts?: client_bank_accountCreateInput[];
  client_contacts?: client_contactCreateInput[];
  client_documents?: client_documentCreateInput[];
  client_files?: client_fileCreateInput[];
  company_address?: company_addressCreateInput;
  company_config?: company_configCreateInput;
  company_contacts?: company_contactCreateInput[];
  company_customer?: company_customerCreateInput;
  company_documents?: company_documentCreateInput[];
  company_files?: company_fileCreateInput[];
  company_invoices?: company_invoiceCreateInput[];
  cost_centers?: cost_centerCreateInput[];
  integrations?: integrationCreateInput[];
  invites?: inviteCreateInput[];
  kanban_templates?: kanban_templateCreateInput[];
  kanban_template_cards?: kanban_template_cardCreateInput[];
  kanban_template_card_types?: kanban_template_card_typeCreateInput[];
  kanban_template_columns?: kanban_template_columnCreateInput[];
  kanban_template_tags?: kanban_template_tagCreateInput[];
  levels?: levelCreateInput[];
  modules?: moduleCreateInput[];
  notifications?: notificationCreateInput[];
  plans?: planCreateInput[];
  profiles?: profileCreateInput[];
  profile_address?: profile_addressCreateInput[];
  profile_bank_accounts?: profile_bank_accountCreateInput[];
  profile_bonus?: profile_bonusCreateInput[];
  profile_contacts?: profile_contactCreateInput[];
  profile_documents?: profile_documentCreateInput[];
  profile_files?: profile_fileCreateInput[];
  profile_roles?: profile_roleCreateInput[];
  projects?: projectCreateInput[];
  project_allocations?: project_allocationCreateInput[];
  project_configs?: project_configCreateInput[];
  project_financials?: project_financialCreateInput[];
  project_financial_employees?: project_financial_employeesCreateInput[];
  project_kanbans?: project_kanbanCreateInput[];
  project_kanban_cycles?: project_kanban_cycleCreateInput[];
  project_kanban_cycle_allocations?: project_kanban_cycle_allocationCreateInput[];
  project_kanban_cycle_cards?: project_kanban_cycle_cardCreateInput[];
  project_kanban_cycle_card_comments?: project_kanban_cycle_card_commentCreateInput[];
  project_kanban_cycle_card_files?: project_kanban_cycle_card_fileCreateInput[];
  project_kanban_cycle_card_reads?: project_kanban_cycle_card_readCreateInput[];
  project_kanban_cycle_card_tags?: project_kanban_cycle_card_tagCreateInput[];
  project_kanban_cycle_card_types?: project_kanban_cycle_card_typeCreateInput[];
  project_kanban_cycle_columns?: project_kanban_cycle_columnCreateInput[];
  project_kanban_objectives?: project_kanban_objectiveCreateInput[];
  project_kanban_objective_targets?: project_kanban_objective_targetCreateInput[];
  project_members?: project_memberCreateInput[];
  project_tools?: project_toolCreateInput[];
  project_versions?: project_versionCreateInput[];
  roles?: roleCreateInput[];
  subscriptions?: subscriptionCreateInput[];
  subscription_changes?: subscription_changesCreateInput[];
  subscription_plans?: subscription_planCreateInput[];
  work_types?: work_typeCreateInput[];
  logs?: log__companyCreateInput[];
}

export type companyUpdateInput = Partial<companyCreateInput>;

