import { project_config } from "@repo/types";

import { Pagination } from "../../../@types";

export const placeholder: Pagination<project_config> = {
  data: [
    {
      id: "1",
      util_hour_day: 1,
      total_hour_day: 1,
      project_version_id: "1",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
      project_id: "1",
      company_id: "1",
    },
    {
      id: "2",
      util_hour_day: 1,
      total_hour_day: 1,
      project_version_id: "2",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
      project_id: "2",
      company_id: "2",
    },
    {
      id: "3",
      util_hour_day: 1,
      total_hour_day: 1,
      project_version_id: "3",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
      project_id: "3",
      company_id: "3",
    },
    {
      id: "4",
      util_hour_day: 1,
      total_hour_day: 1,
      project_version_id: "4",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
      project_id: "4",
      company_id: "4",
    },
    {
      id: "5",
      util_hour_day: 1,
      total_hour_day: 1,
      project_version_id: "5",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deleted: false,
      deletedAt: null,
      project_id: "5",
      company_id: "5",
    },
  ],
  page: 1,
  pages: 1,
  count: 0,
};
