import { company, companyCreateInput } from "./company";
import { integration_action, integration_actionCreateInput } from "./integration_action";
import { log__integration, log__integrationCreateInput } from "./log__integration";
import { log__client, log__clientCreateInput } from "./log__client";
import { log__client_address, log__client_addressCreateInput } from "./log__client_address";
import { log__client_contact, log__client_contactCreateInput } from "./log__client_contact";
import { log__client_document, log__client_documentCreateInput } from "./log__client_document";
import { log__company, log__companyCreateInput } from "./log__company";
import { log__company_address, log__company_addressCreateInput } from "./log__company_address";
import { log__company_contact, log__company_contactCreateInput } from "./log__company_contact";
import { log__company_document, log__company_documentCreateInput } from "./log__company_document";
import { log__level, log__levelCreateInput } from "./log__level";
import { log__profile_address, log__profile_addressCreateInput } from "./log__profile_address";
import { log__profile_contact, log__profile_contactCreateInput } from "./log__profile_contact";
import { log__profile_document, log__profile_documentCreateInput } from "./log__profile_document";
import { log__cost_center, log__cost_centerCreateInput } from "./log__cost_center";
import { log__role, log__roleCreateInput } from "./log__role";
import { log__profile_role, log__profile_roleCreateInput } from "./log__profile_role";
import { log__profile_bonus, log__profile_bonusCreateInput } from "./log__profile_bonus";
import { log__project, log__projectCreateInput } from "./log__project";
import { log__project_version, log__project_versionCreateInput } from "./log__project_version";
import { log__work_type, log__work_typeCreateInput } from "./log__work_type";
import { log__project_financial, log__project_financialCreateInput } from "./log__project_financial";
import { log__project_financial_employees, log__project_financial_employeesCreateInput } from "./log__project_financial_employees";
import { log__project_member, log__project_memberCreateInput } from "./log__project_member";
import { log__kanban_template, log__kanban_templateCreateInput } from "./log__kanban_template";
import { log__kanban_template_card, log__kanban_template_cardCreateInput } from "./log__kanban_template_card";
import { log__kanban_template_column, log__kanban_template_columnCreateInput } from "./log__kanban_template_column";
import { log__project_kanban, log__project_kanbanCreateInput } from "./log__project_kanban";
import { log__project_kanban_cycle, log__project_kanban_cycleCreateInput } from "./log__project_kanban_cycle";
import { log__project_kanban_cycle_card_type, log__project_kanban_cycle_card_typeCreateInput } from "./log__project_kanban_cycle_card_type";
import { log__project_kanban_cycle_column, log__project_kanban_cycle_columnCreateInput } from "./log__project_kanban_cycle_column";
import { log__project_kanban_cycle_card, log__project_kanban_cycle_cardCreateInput } from "./log__project_kanban_cycle_card";
import { log__project_kanban_cycle_allocation, log__project_kanban_cycle_allocationCreateInput } from "./log__project_kanban_cycle_allocation";
import { log__kanban_template_card_type, log__kanban_template_card_typeCreateInput } from "./log__kanban_template_card_type";
import { log__profile, log__profileCreateInput } from "./log__profile";
import { log__invite, log__inviteCreateInput } from "./log__invite";
import { log__client_file, log__client_fileCreateInput } from "./log__client_file";
import { log__company_file, log__company_fileCreateInput } from "./log__company_file";
import { log__feature, log__featureCreateInput } from "./log__feature";
import { log__profile_file, log__profile_fileCreateInput } from "./log__profile_file";
import { log__user, log__userCreateInput } from "./log__user";
import { log__kanban_template_tag, log__kanban_template_tagCreateInput } from "./log__kanban_template_tag";
import { log__project_kanban_cycle_card_file, log__project_kanban_cycle_card_fileCreateInput } from "./log__project_kanban_cycle_card_file";
import { log__project_kanban_objective, log__project_kanban_objectiveCreateInput } from "./log__project_kanban_objective";
import { log__project_kanban_objective_target, log__project_kanban_objective_targetCreateInput } from "./log__project_kanban_objective_target";
import { log__company_config, log__company_configCreateInput } from "./log__company_config";
import { log__project_config, log__project_configCreateInput } from "./log__project_config";
import { log__project_allocation, log__project_allocationCreateInput } from "./log__project_allocation";
import { log__client_bank_account, log__client_bank_accountCreateInput } from "./log__client_bank_account";
import { log__profile_bank_account, log__profile_bank_accountCreateInput } from "./log__profile_bank_account";
import { log__project_tool, log__project_toolCreateInput } from "./log__project_tool";

export interface integration {
  id: string;
  deleted: boolean;
  deletedAt: string | null;
  updatedAt: string;
  createdAt: string;
  name: string;
  company_id: string;
  token: string;
  expire_in: string | null;
  active: boolean;
  company?: company;
  integration_actions?: integration_action[];
  logs?: log__integration[];
  log__client_integration?: log__client[];
  log__client_address_integration?: log__client_address[];
  log__client_contact_integration?: log__client_contact[];
  log__client_document_integration?: log__client_document[];
  log__company_integration?: log__company[];
  log__company_address_integration?: log__company_address[];
  log__company_contact_integration?: log__company_contact[];
  log__company_document_integration?: log__company_document[];
  log__integration_integration?: log__integration[];
  log__level_integration?: log__level[];
  log__profile_address_integration?: log__profile_address[];
  log__profile_contact_integration?: log__profile_contact[];
  log__profile_document_integration?: log__profile_document[];
  log__cost_center_integration?: log__cost_center[];
  log__role_integration?: log__role[];
  log__profile_role_integration?: log__profile_role[];
  log__profile_bonus_integration?: log__profile_bonus[];
  log__project_integration?: log__project[];
  log__project_version_integration?: log__project_version[];
  log__work_type_integration?: log__work_type[];
  log__project_financial_integration?: log__project_financial[];
  log__project_financial_employees_integration?: log__project_financial_employees[];
  log__project_member_integration?: log__project_member[];
  log__kanban_template_integration?: log__kanban_template[];
  log__kanban_template_card_integration?: log__kanban_template_card[];
  log__kanban_template_column_integration?: log__kanban_template_column[];
  log__project_kanban_integration?: log__project_kanban[];
  log__project_kanban_cycle_integration?: log__project_kanban_cycle[];
  log__project_kanban_cycle_card_type_integration?: log__project_kanban_cycle_card_type[];
  log__project_kanban_cycle_column_integration?: log__project_kanban_cycle_column[];
  log__project_kanban_cycle_card_integration?: log__project_kanban_cycle_card[];
  log__project_kanban_cycle_allocation_integration?: log__project_kanban_cycle_allocation[];
  log__kanban_template_card_type_integration?: log__kanban_template_card_type[];
  log__profile_integration?: log__profile[];
  log__invite_integration?: log__invite[];
  log__client_file_integration?: log__client_file[];
  log__company_file_integration?: log__company_file[];
  log__feature_integration?: log__feature[];
  log__profile_file_integration?: log__profile_file[];
  log__user_integration?: log__user[];
  log__kanban_template_tag_integration?: log__kanban_template_tag[];
  log__project_kanban_cycle_card_file_integration?: log__project_kanban_cycle_card_file[];
  log__project_kanban_objective_integration?: log__project_kanban_objective[];
  log__project_kanban_objective_target_integration?: log__project_kanban_objective_target[];
  log__company_config_integration?: log__company_config[];
  log__project_config_integration?: log__project_config[];
  log__project_allocation_integration?: log__project_allocation[];
  log__client_bank_account_integration?: log__client_bank_account[];
  log__profile_bank_account_integration?: log__profile_bank_account[];
  log__project_tool_integration?: log__project_tool[];
}

export interface integrationCreateInput {
  id?: string;
  deleted?: boolean;
  deletedAt?: string | null;
  updatedAt?: string;
  createdAt?: string;
  name: string;
  company_id?: string;
  token: string;
  expire_in?: string | null;
  active?: boolean;
  company?: companyCreateInput;
  integration_actions?: integration_actionCreateInput[];
  logs?: log__integrationCreateInput[];
  log__client_integration?: log__clientCreateInput[];
  log__client_address_integration?: log__client_addressCreateInput[];
  log__client_contact_integration?: log__client_contactCreateInput[];
  log__client_document_integration?: log__client_documentCreateInput[];
  log__company_integration?: log__companyCreateInput[];
  log__company_address_integration?: log__company_addressCreateInput[];
  log__company_contact_integration?: log__company_contactCreateInput[];
  log__company_document_integration?: log__company_documentCreateInput[];
  log__integration_integration?: log__integrationCreateInput[];
  log__level_integration?: log__levelCreateInput[];
  log__profile_address_integration?: log__profile_addressCreateInput[];
  log__profile_contact_integration?: log__profile_contactCreateInput[];
  log__profile_document_integration?: log__profile_documentCreateInput[];
  log__cost_center_integration?: log__cost_centerCreateInput[];
  log__role_integration?: log__roleCreateInput[];
  log__profile_role_integration?: log__profile_roleCreateInput[];
  log__profile_bonus_integration?: log__profile_bonusCreateInput[];
  log__project_integration?: log__projectCreateInput[];
  log__project_version_integration?: log__project_versionCreateInput[];
  log__work_type_integration?: log__work_typeCreateInput[];
  log__project_financial_integration?: log__project_financialCreateInput[];
  log__project_financial_employees_integration?: log__project_financial_employeesCreateInput[];
  log__project_member_integration?: log__project_memberCreateInput[];
  log__kanban_template_integration?: log__kanban_templateCreateInput[];
  log__kanban_template_card_integration?: log__kanban_template_cardCreateInput[];
  log__kanban_template_column_integration?: log__kanban_template_columnCreateInput[];
  log__project_kanban_integration?: log__project_kanbanCreateInput[];
  log__project_kanban_cycle_integration?: log__project_kanban_cycleCreateInput[];
  log__project_kanban_cycle_card_type_integration?: log__project_kanban_cycle_card_typeCreateInput[];
  log__project_kanban_cycle_column_integration?: log__project_kanban_cycle_columnCreateInput[];
  log__project_kanban_cycle_card_integration?: log__project_kanban_cycle_cardCreateInput[];
  log__project_kanban_cycle_allocation_integration?: log__project_kanban_cycle_allocationCreateInput[];
  log__kanban_template_card_type_integration?: log__kanban_template_card_typeCreateInput[];
  log__profile_integration?: log__profileCreateInput[];
  log__invite_integration?: log__inviteCreateInput[];
  log__client_file_integration?: log__client_fileCreateInput[];
  log__company_file_integration?: log__company_fileCreateInput[];
  log__feature_integration?: log__featureCreateInput[];
  log__profile_file_integration?: log__profile_fileCreateInput[];
  log__user_integration?: log__userCreateInput[];
  log__kanban_template_tag_integration?: log__kanban_template_tagCreateInput[];
  log__project_kanban_cycle_card_file_integration?: log__project_kanban_cycle_card_fileCreateInput[];
  log__project_kanban_objective_integration?: log__project_kanban_objectiveCreateInput[];
  log__project_kanban_objective_target_integration?: log__project_kanban_objective_targetCreateInput[];
  log__company_config_integration?: log__company_configCreateInput[];
  log__project_config_integration?: log__project_configCreateInput[];
  log__project_allocation_integration?: log__project_allocationCreateInput[];
  log__client_bank_account_integration?: log__client_bank_accountCreateInput[];
  log__profile_bank_account_integration?: log__profile_bank_accountCreateInput[];
  log__project_tool_integration?: log__project_toolCreateInput[];
}

export type integrationUpdateInput = Partial<integrationCreateInput>;

