import { profile, profileCreateInput } from "./profile";
import { company, companyCreateInput } from "./company";
import { notification, notificationCreateInput } from "./notification";
import { notification_subscription, notification_subscriptionCreateInput } from "./notification_subscription";
import { user_token, user_tokenCreateInput } from "./user_token";
import { user_two_auth, user_two_authCreateInput } from "./user_two_auth";
import { log__client, log__clientCreateInput } from "./log__client";
import { log__client_address, log__client_addressCreateInput } from "./log__client_address";
import { log__client_bank_account, log__client_bank_accountCreateInput } from "./log__client_bank_account";
import { log__client_contact, log__client_contactCreateInput } from "./log__client_contact";
import { log__client_document, log__client_documentCreateInput } from "./log__client_document";
import { log__client_file, log__client_fileCreateInput } from "./log__client_file";
import { log__company, log__companyCreateInput } from "./log__company";
import { log__company_address, log__company_addressCreateInput } from "./log__company_address";
import { log__company_config, log__company_configCreateInput } from "./log__company_config";
import { log__company_contact, log__company_contactCreateInput } from "./log__company_contact";
import { log__company_document, log__company_documentCreateInput } from "./log__company_document";
import { log__company_file, log__company_fileCreateInput } from "./log__company_file";
import { log__cost_center, log__cost_centerCreateInput } from "./log__cost_center";
import { log__feature, log__featureCreateInput } from "./log__feature";
import { log__integration, log__integrationCreateInput } from "./log__integration";
import { log__invite, log__inviteCreateInput } from "./log__invite";
import { log__kanban_template, log__kanban_templateCreateInput } from "./log__kanban_template";
import { log__kanban_template_card, log__kanban_template_cardCreateInput } from "./log__kanban_template_card";
import { log__kanban_template_card_type, log__kanban_template_card_typeCreateInput } from "./log__kanban_template_card_type";
import { log__kanban_template_column, log__kanban_template_columnCreateInput } from "./log__kanban_template_column";
import { log__kanban_template_tag, log__kanban_template_tagCreateInput } from "./log__kanban_template_tag";
import { log__level, log__levelCreateInput } from "./log__level";
import { log__profile, log__profileCreateInput } from "./log__profile";
import { log__profile_address, log__profile_addressCreateInput } from "./log__profile_address";
import { log__profile_bank_account, log__profile_bank_accountCreateInput } from "./log__profile_bank_account";
import { log__profile_bonus, log__profile_bonusCreateInput } from "./log__profile_bonus";
import { log__profile_contact, log__profile_contactCreateInput } from "./log__profile_contact";
import { log__profile_document, log__profile_documentCreateInput } from "./log__profile_document";
import { log__profile_file, log__profile_fileCreateInput } from "./log__profile_file";
import { log__profile_role, log__profile_roleCreateInput } from "./log__profile_role";
import { log__project, log__projectCreateInput } from "./log__project";
import { log__project_allocation, log__project_allocationCreateInput } from "./log__project_allocation";
import { log__project_config, log__project_configCreateInput } from "./log__project_config";
import { log__project_financial, log__project_financialCreateInput } from "./log__project_financial";
import { log__project_financial_employees, log__project_financial_employeesCreateInput } from "./log__project_financial_employees";
import { log__project_kanban, log__project_kanbanCreateInput } from "./log__project_kanban";
import { log__project_kanban_cycle, log__project_kanban_cycleCreateInput } from "./log__project_kanban_cycle";
import { log__project_kanban_cycle_allocation, log__project_kanban_cycle_allocationCreateInput } from "./log__project_kanban_cycle_allocation";
import { log__project_kanban_cycle_card, log__project_kanban_cycle_cardCreateInput } from "./log__project_kanban_cycle_card";
import { log__project_kanban_cycle_card_file, log__project_kanban_cycle_card_fileCreateInput } from "./log__project_kanban_cycle_card_file";
import { log__project_kanban_cycle_card_type, log__project_kanban_cycle_card_typeCreateInput } from "./log__project_kanban_cycle_card_type";
import { log__project_kanban_cycle_column, log__project_kanban_cycle_columnCreateInput } from "./log__project_kanban_cycle_column";
import { log__project_kanban_objective, log__project_kanban_objectiveCreateInput } from "./log__project_kanban_objective";
import { log__project_kanban_objective_target, log__project_kanban_objective_targetCreateInput } from "./log__project_kanban_objective_target";
import { log__project_member, log__project_memberCreateInput } from "./log__project_member";
import { log__project_tool, log__project_toolCreateInput } from "./log__project_tool";
import { log__project_version, log__project_versionCreateInput } from "./log__project_version";
import { log__role, log__roleCreateInput } from "./log__role";
import { log__user, log__userCreateInput } from "./log__user";
import { log__work_type, log__work_typeCreateInput } from "./log__work_type";

export interface user {
  id: string;
  deleted: boolean;
  deletedAt: string | null;
  updatedAt: string;
  createdAt: string;
  name: string;
  avatar: string | null;
  provider: string;
  email: string;
  active: boolean;
  password: string | null;
  password_confirm: string | null;
  need_reset: boolean;
  confirmed: boolean;
  confirmed_date: string | null;
  recovery_code: string | null;
  recovery_date: string | null;
  confirm_code: string | null;
  confirm_date: string | null;
  default_profile_id: string | null;
  avatar_original_name: string | null;
  default_profile?: profile;
  companies?: company[];
  notifications?: notification[];
  notification_subscriptions?: notification_subscription[];
  profiles?: profile[];
  user_tokens?: user_token[];
  user_two_auths?: user_two_auth[];
  log__client_api?: log__client[];
  log__client_address_api?: log__client_address[];
  log__client_bank_account_api?: log__client_bank_account[];
  log__client_contact_api?: log__client_contact[];
  log__client_document_api?: log__client_document[];
  log__client_file_api?: log__client_file[];
  log__company_api?: log__company[];
  log__company_address_api?: log__company_address[];
  log__company_config_api?: log__company_config[];
  log__company_contact_api?: log__company_contact[];
  log__company_document_api?: log__company_document[];
  log__company_file_api?: log__company_file[];
  log__cost_center_api?: log__cost_center[];
  log__feature_api?: log__feature[];
  log__integration_api?: log__integration[];
  log__invite_api?: log__invite[];
  log__kanban_template_api?: log__kanban_template[];
  log__kanban_template_card_api?: log__kanban_template_card[];
  log__kanban_template_card_type_api?: log__kanban_template_card_type[];
  log__kanban_template_column_api?: log__kanban_template_column[];
  log__kanban_template_tag_api?: log__kanban_template_tag[];
  log__level_api?: log__level[];
  log__profile_api?: log__profile[];
  log__profile_address_api?: log__profile_address[];
  log__profile_bank_account_api?: log__profile_bank_account[];
  log__profile_bonus_api?: log__profile_bonus[];
  log__profile_contact_api?: log__profile_contact[];
  log__profile_document_api?: log__profile_document[];
  log__profile_file_api?: log__profile_file[];
  log__profile_role_api?: log__profile_role[];
  log__project_api?: log__project[];
  log__project_allocation_api?: log__project_allocation[];
  log__project_config_api?: log__project_config[];
  log__project_financial_api?: log__project_financial[];
  log__project_financial_employees_api?: log__project_financial_employees[];
  log__project_kanban_api?: log__project_kanban[];
  log__project_kanban_cycle_api?: log__project_kanban_cycle[];
  log__project_kanban_cycle_allocation_api?: log__project_kanban_cycle_allocation[];
  log__project_kanban_cycle_card_api?: log__project_kanban_cycle_card[];
  log__project_kanban_cycle_card_file_api?: log__project_kanban_cycle_card_file[];
  log__project_kanban_cycle_card_type_api?: log__project_kanban_cycle_card_type[];
  log__project_kanban_cycle_column_api?: log__project_kanban_cycle_column[];
  log__project_kanban_objective_api?: log__project_kanban_objective[];
  log__project_kanban_objective_target_api?: log__project_kanban_objective_target[];
  log__project_member_api?: log__project_member[];
  log__project_tool_api?: log__project_tool[];
  log__project_version_api?: log__project_version[];
  log__role_api?: log__role[];
  logs?: log__user[];
  log__user_api?: log__user[];
  log__work_type_api?: log__work_type[];
}

export interface userCreateInput {
  id?: string;
  deleted?: boolean;
  deletedAt?: string | null;
  updatedAt?: string;
  createdAt?: string;
  name: string;
  avatar?: string | null;
  provider?: string;
  email: string;
  active?: boolean;
  password?: string | null;
  password_confirm?: string | null;
  need_reset?: boolean;
  confirmed?: boolean;
  confirmed_date?: string | null;
  recovery_code?: string | null;
  recovery_date?: string | null;
  confirm_code?: string | null;
  confirm_date?: string | null;
  default_profile_id?: string | null;
  avatar_original_name?: string | null;
  default_profile?: profileCreateInput;
  companies?: companyCreateInput[];
  notifications?: notificationCreateInput[];
  notification_subscriptions?: notification_subscriptionCreateInput[];
  profiles?: profileCreateInput[];
  user_tokens?: user_tokenCreateInput[];
  user_two_auths?: user_two_authCreateInput[];
  log__client_api?: log__clientCreateInput[];
  log__client_address_api?: log__client_addressCreateInput[];
  log__client_bank_account_api?: log__client_bank_accountCreateInput[];
  log__client_contact_api?: log__client_contactCreateInput[];
  log__client_document_api?: log__client_documentCreateInput[];
  log__client_file_api?: log__client_fileCreateInput[];
  log__company_api?: log__companyCreateInput[];
  log__company_address_api?: log__company_addressCreateInput[];
  log__company_config_api?: log__company_configCreateInput[];
  log__company_contact_api?: log__company_contactCreateInput[];
  log__company_document_api?: log__company_documentCreateInput[];
  log__company_file_api?: log__company_fileCreateInput[];
  log__cost_center_api?: log__cost_centerCreateInput[];
  log__feature_api?: log__featureCreateInput[];
  log__integration_api?: log__integrationCreateInput[];
  log__invite_api?: log__inviteCreateInput[];
  log__kanban_template_api?: log__kanban_templateCreateInput[];
  log__kanban_template_card_api?: log__kanban_template_cardCreateInput[];
  log__kanban_template_card_type_api?: log__kanban_template_card_typeCreateInput[];
  log__kanban_template_column_api?: log__kanban_template_columnCreateInput[];
  log__kanban_template_tag_api?: log__kanban_template_tagCreateInput[];
  log__level_api?: log__levelCreateInput[];
  log__profile_api?: log__profileCreateInput[];
  log__profile_address_api?: log__profile_addressCreateInput[];
  log__profile_bank_account_api?: log__profile_bank_accountCreateInput[];
  log__profile_bonus_api?: log__profile_bonusCreateInput[];
  log__profile_contact_api?: log__profile_contactCreateInput[];
  log__profile_document_api?: log__profile_documentCreateInput[];
  log__profile_file_api?: log__profile_fileCreateInput[];
  log__profile_role_api?: log__profile_roleCreateInput[];
  log__project_api?: log__projectCreateInput[];
  log__project_allocation_api?: log__project_allocationCreateInput[];
  log__project_config_api?: log__project_configCreateInput[];
  log__project_financial_api?: log__project_financialCreateInput[];
  log__project_financial_employees_api?: log__project_financial_employeesCreateInput[];
  log__project_kanban_api?: log__project_kanbanCreateInput[];
  log__project_kanban_cycle_api?: log__project_kanban_cycleCreateInput[];
  log__project_kanban_cycle_allocation_api?: log__project_kanban_cycle_allocationCreateInput[];
  log__project_kanban_cycle_card_api?: log__project_kanban_cycle_cardCreateInput[];
  log__project_kanban_cycle_card_file_api?: log__project_kanban_cycle_card_fileCreateInput[];
  log__project_kanban_cycle_card_type_api?: log__project_kanban_cycle_card_typeCreateInput[];
  log__project_kanban_cycle_column_api?: log__project_kanban_cycle_columnCreateInput[];
  log__project_kanban_objective_api?: log__project_kanban_objectiveCreateInput[];
  log__project_kanban_objective_target_api?: log__project_kanban_objective_targetCreateInput[];
  log__project_member_api?: log__project_memberCreateInput[];
  log__project_tool_api?: log__project_toolCreateInput[];
  log__project_version_api?: log__project_versionCreateInput[];
  log__role_api?: log__roleCreateInput[];
  logs?: log__userCreateInput[];
  log__user_api?: log__userCreateInput[];
  log__work_type_api?: log__work_typeCreateInput[];
}

export type userUpdateInput = Partial<userCreateInput>;

