import { admin_token, admin_tokenCreateInput } from "./admin_token";
import { log__client, log__clientCreateInput } from "./log__client";
import { log__client_address, log__client_addressCreateInput } from "./log__client_address";
import { log__client_contact, log__client_contactCreateInput } from "./log__client_contact";
import { log__client_document, log__client_documentCreateInput } from "./log__client_document";
import { log__company, log__companyCreateInput } from "./log__company";
import { log__company_address, log__company_addressCreateInput } from "./log__company_address";
import { log__company_contact, log__company_contactCreateInput } from "./log__company_contact";
import { log__company_document, log__company_documentCreateInput } from "./log__company_document";
import { log__level, log__levelCreateInput } from "./log__level";
import { log__integration, log__integrationCreateInput } from "./log__integration";
import { log__profile_address, log__profile_addressCreateInput } from "./log__profile_address";
import { log__profile_contact, log__profile_contactCreateInput } from "./log__profile_contact";
import { log__profile_document, log__profile_documentCreateInput } from "./log__profile_document";
import { log__cost_center, log__cost_centerCreateInput } from "./log__cost_center";
import { log__role, log__roleCreateInput } from "./log__role";
import { log__profile_role, log__profile_roleCreateInput } from "./log__profile_role";
import { log__profile_bonus, log__profile_bonusCreateInput } from "./log__profile_bonus";
import { log__project, log__projectCreateInput } from "./log__project";
import { log__project_version, log__project_versionCreateInput } from "./log__project_version";
import { log__work_type, log__work_typeCreateInput } from "./log__work_type";
import { log__project_financial, log__project_financialCreateInput } from "./log__project_financial";
import { log__project_financial_employees, log__project_financial_employeesCreateInput } from "./log__project_financial_employees";
import { log__project_member, log__project_memberCreateInput } from "./log__project_member";
import { log__kanban_template, log__kanban_templateCreateInput } from "./log__kanban_template";
import { log__kanban_template_card, log__kanban_template_cardCreateInput } from "./log__kanban_template_card";
import { log__kanban_template_column, log__kanban_template_columnCreateInput } from "./log__kanban_template_column";
import { log__project_kanban, log__project_kanbanCreateInput } from "./log__project_kanban";
import { log__project_kanban_cycle, log__project_kanban_cycleCreateInput } from "./log__project_kanban_cycle";
import { log__project_kanban_cycle_card_type, log__project_kanban_cycle_card_typeCreateInput } from "./log__project_kanban_cycle_card_type";
import { log__project_kanban_cycle_column, log__project_kanban_cycle_columnCreateInput } from "./log__project_kanban_cycle_column";
import { log__project_kanban_cycle_card, log__project_kanban_cycle_cardCreateInput } from "./log__project_kanban_cycle_card";
import { log__project_kanban_cycle_allocation, log__project_kanban_cycle_allocationCreateInput } from "./log__project_kanban_cycle_allocation";
import { log__kanban_template_card_type, log__kanban_template_card_typeCreateInput } from "./log__kanban_template_card_type";
import { log__profile, log__profileCreateInput } from "./log__profile";
import { log__invite, log__inviteCreateInput } from "./log__invite";
import { log__client_file, log__client_fileCreateInput } from "./log__client_file";
import { log__company_file, log__company_fileCreateInput } from "./log__company_file";
import { log__feature, log__featureCreateInput } from "./log__feature";
import { log__profile_file, log__profile_fileCreateInput } from "./log__profile_file";
import { log__user, log__userCreateInput } from "./log__user";
import { log__kanban_template_tag, log__kanban_template_tagCreateInput } from "./log__kanban_template_tag";
import { log__project_kanban_cycle_card_file, log__project_kanban_cycle_card_fileCreateInput } from "./log__project_kanban_cycle_card_file";
import { log__project_kanban_objective, log__project_kanban_objectiveCreateInput } from "./log__project_kanban_objective";
import { log__project_kanban_objective_target, log__project_kanban_objective_targetCreateInput } from "./log__project_kanban_objective_target";
import { log__company_config, log__company_configCreateInput } from "./log__company_config";
import { log__project_config, log__project_configCreateInput } from "./log__project_config";
import { log__project_allocation, log__project_allocationCreateInput } from "./log__project_allocation";
import { log__client_bank_account, log__client_bank_accountCreateInput } from "./log__client_bank_account";
import { log__profile_bank_account, log__profile_bank_accountCreateInput } from "./log__profile_bank_account";
import { log__project_tool, log__project_toolCreateInput } from "./log__project_tool";

export interface admin {
  id: string;
  deleted: boolean;
  deletedAt: string | null;
  updatedAt: string;
  createdAt: string;
  name: string;
  password: string | null;
  password_confirm: string | null;
  email: string;
  active: boolean;
  need_reset: boolean;
  confirmed: boolean;
  confirmed_date: string | null;
  recovery_code: string | null;
  recovery_date: string | null;
  confirm_code: string | null;
  confirm_date: string | null;
  admin_tokens?: admin_token[];
  log__client_manager?: log__client[];
  log__client_address_manager?: log__client_address[];
  log__client_contact_manager?: log__client_contact[];
  log__client_document_manager?: log__client_document[];
  log__company_manager?: log__company[];
  log__company_address_manager?: log__company_address[];
  log__company_contact_manager?: log__company_contact[];
  log__company_document_manager?: log__company_document[];
  log__level_manager?: log__level[];
  log__integration_manager?: log__integration[];
  log__profile_address_manager?: log__profile_address[];
  log__profile_contact_manager?: log__profile_contact[];
  log__profile_document_manager?: log__profile_document[];
  log__cost_center_manager?: log__cost_center[];
  log__role_manager?: log__role[];
  log__profile_role_manager?: log__profile_role[];
  log__profile_bonus_manager?: log__profile_bonus[];
  log__project_manager?: log__project[];
  log__project_version_manager?: log__project_version[];
  log__work_type_manager?: log__work_type[];
  log__project_financial_manager?: log__project_financial[];
  log__project_financial_employees_manager?: log__project_financial_employees[];
  log__project_member_manager?: log__project_member[];
  log__kanban_template_manager?: log__kanban_template[];
  log__kanban_template_card_manager?: log__kanban_template_card[];
  log__kanban_template_column_manager?: log__kanban_template_column[];
  log__project_kanban_manager?: log__project_kanban[];
  log__project_kanban_cycle_manager?: log__project_kanban_cycle[];
  log__project_kanban_cycle_card_type_manager?: log__project_kanban_cycle_card_type[];
  log__project_kanban_cycle_column_manager?: log__project_kanban_cycle_column[];
  log__project_kanban_cycle_card_manager?: log__project_kanban_cycle_card[];
  log__project_kanban_cycle_allocation_manager?: log__project_kanban_cycle_allocation[];
  log__kanban_template_card_type_manager?: log__kanban_template_card_type[];
  log__profile_manager?: log__profile[];
  log__invite_manager?: log__invite[];
  log__client_file_manager?: log__client_file[];
  log__company_file_manager?: log__company_file[];
  log__feature_manager?: log__feature[];
  log__profile_file_manager?: log__profile_file[];
  log__user_manager?: log__user[];
  log__kanban_template_tag_manager?: log__kanban_template_tag[];
  log__project_kanban_cycle_card_file_manager?: log__project_kanban_cycle_card_file[];
  log__project_kanban_objective_manager?: log__project_kanban_objective[];
  log__project_kanban_objective_target_manager?: log__project_kanban_objective_target[];
  log__company_config_manager?: log__company_config[];
  log__project_config_manager?: log__project_config[];
  log__project_allocation_manager?: log__project_allocation[];
  log__client_bank_account_manager?: log__client_bank_account[];
  log__profile_bank_account_manager?: log__profile_bank_account[];
  log__project_tool_manager?: log__project_tool[];
}

export interface adminCreateInput {
  id?: string;
  deleted?: boolean;
  deletedAt?: string | null;
  updatedAt?: string;
  createdAt?: string;
  name: string;
  password?: string | null;
  password_confirm?: string | null;
  email: string;
  active?: boolean;
  need_reset?: boolean;
  confirmed?: boolean;
  confirmed_date?: string | null;
  recovery_code?: string | null;
  recovery_date?: string | null;
  confirm_code?: string | null;
  confirm_date?: string | null;
  admin_tokens?: admin_tokenCreateInput[];
  log__client_manager?: log__clientCreateInput[];
  log__client_address_manager?: log__client_addressCreateInput[];
  log__client_contact_manager?: log__client_contactCreateInput[];
  log__client_document_manager?: log__client_documentCreateInput[];
  log__company_manager?: log__companyCreateInput[];
  log__company_address_manager?: log__company_addressCreateInput[];
  log__company_contact_manager?: log__company_contactCreateInput[];
  log__company_document_manager?: log__company_documentCreateInput[];
  log__level_manager?: log__levelCreateInput[];
  log__integration_manager?: log__integrationCreateInput[];
  log__profile_address_manager?: log__profile_addressCreateInput[];
  log__profile_contact_manager?: log__profile_contactCreateInput[];
  log__profile_document_manager?: log__profile_documentCreateInput[];
  log__cost_center_manager?: log__cost_centerCreateInput[];
  log__role_manager?: log__roleCreateInput[];
  log__profile_role_manager?: log__profile_roleCreateInput[];
  log__profile_bonus_manager?: log__profile_bonusCreateInput[];
  log__project_manager?: log__projectCreateInput[];
  log__project_version_manager?: log__project_versionCreateInput[];
  log__work_type_manager?: log__work_typeCreateInput[];
  log__project_financial_manager?: log__project_financialCreateInput[];
  log__project_financial_employees_manager?: log__project_financial_employeesCreateInput[];
  log__project_member_manager?: log__project_memberCreateInput[];
  log__kanban_template_manager?: log__kanban_templateCreateInput[];
  log__kanban_template_card_manager?: log__kanban_template_cardCreateInput[];
  log__kanban_template_column_manager?: log__kanban_template_columnCreateInput[];
  log__project_kanban_manager?: log__project_kanbanCreateInput[];
  log__project_kanban_cycle_manager?: log__project_kanban_cycleCreateInput[];
  log__project_kanban_cycle_card_type_manager?: log__project_kanban_cycle_card_typeCreateInput[];
  log__project_kanban_cycle_column_manager?: log__project_kanban_cycle_columnCreateInput[];
  log__project_kanban_cycle_card_manager?: log__project_kanban_cycle_cardCreateInput[];
  log__project_kanban_cycle_allocation_manager?: log__project_kanban_cycle_allocationCreateInput[];
  log__kanban_template_card_type_manager?: log__kanban_template_card_typeCreateInput[];
  log__profile_manager?: log__profileCreateInput[];
  log__invite_manager?: log__inviteCreateInput[];
  log__client_file_manager?: log__client_fileCreateInput[];
  log__company_file_manager?: log__company_fileCreateInput[];
  log__feature_manager?: log__featureCreateInput[];
  log__profile_file_manager?: log__profile_fileCreateInput[];
  log__user_manager?: log__userCreateInput[];
  log__kanban_template_tag_manager?: log__kanban_template_tagCreateInput[];
  log__project_kanban_cycle_card_file_manager?: log__project_kanban_cycle_card_fileCreateInput[];
  log__project_kanban_objective_manager?: log__project_kanban_objectiveCreateInput[];
  log__project_kanban_objective_target_manager?: log__project_kanban_objective_targetCreateInput[];
  log__company_config_manager?: log__company_configCreateInput[];
  log__project_config_manager?: log__project_configCreateInput[];
  log__project_allocation_manager?: log__project_allocationCreateInput[];
  log__client_bank_account_manager?: log__client_bank_accountCreateInput[];
  log__profile_bank_account_manager?: log__profile_bank_accountCreateInput[];
  log__project_tool_manager?: log__project_toolCreateInput[];
}

export type adminUpdateInput = Partial<adminCreateInput>;

