import { user, userCreateInput } from "./user";
import { level, levelCreateInput } from "./level";
import { company, companyCreateInput } from "./company";
import { chat, chatCreateInput } from "./chat";
import { kanban_template, kanban_templateCreateInput } from "./kanban_template";
import { profile_address, profile_addressCreateInput } from "./profile_address";
import { profile_bank_account, profile_bank_accountCreateInput } from "./profile_bank_account";
import { profile_bonus, profile_bonusCreateInput } from "./profile_bonus";
import { profile_contact, profile_contactCreateInput } from "./profile_contact";
import { profile_document, profile_documentCreateInput } from "./profile_document";
import { profile_file, profile_fileCreateInput } from "./profile_file";
import { profile_role, profile_roleCreateInput } from "./profile_role";
import { project_allocation, project_allocationCreateInput } from "./project_allocation";
import { project_kanban, project_kanbanCreateInput } from "./project_kanban";
import { project_kanban_cycle_allocation, project_kanban_cycle_allocationCreateInput } from "./project_kanban_cycle_allocation";
import { project_kanban_cycle_card, project_kanban_cycle_cardCreateInput } from "./project_kanban_cycle_card";
import { project_kanban_cycle_card_comment, project_kanban_cycle_card_commentCreateInput } from "./project_kanban_cycle_card_comment";
import { project_kanban_cycle_card_read, project_kanban_cycle_card_readCreateInput } from "./project_kanban_cycle_card_read";
import { project_member, project_memberCreateInput } from "./project_member";
import { project_version, project_versionCreateInput } from "./project_version";
import { log__profile, log__profileCreateInput } from "./log__profile";

export interface profile {
  id: string;
  deleted: boolean;
  deletedAt: string | null;
  updatedAt: string;
  createdAt: string;
  user_id: string | null;
  level_id: string | null;
  company_id: string;
  active: boolean;
  type: string | null;
  entity: string | null;
  phone: string | null;
  owner: boolean;
  anonymous: boolean;
  anonymous_name: string | null;
  anonymous_email: string | null;
  anonymous_avatar: string | null;
  user?: user;
  level?: level;
  company?: company;
  chats?: chat[];
  kanban_templates?: kanban_template[];
  profile_address?: profile_address;
  profile_bank_accounts?: profile_bank_account[];
  profile_bonus?: profile_bonus[];
  profile_contacts?: profile_contact[];
  profile_documents?: profile_document[];
  profile_files?: profile_file[];
  profile_roles?: profile_role[];
  project_allocations?: project_allocation[];
  project_kanbans?: project_kanban[];
  project_kanban_cycle_allocations?: project_kanban_cycle_allocation[];
  project_kanban_cycle_cards?: project_kanban_cycle_card[];
  project_kanban_cycle_card_comments?: project_kanban_cycle_card_comment[];
  project_kanban_cycle_card_reads?: project_kanban_cycle_card_read[];
  project_members?: project_member[];
  project_versions?: project_version[];
  users_by_default_profile?: user;
  logs?: log__profile[];
}

export interface profileCreateInput {
  id?: string;
  deleted?: boolean;
  deletedAt?: string | null;
  updatedAt?: string;
  createdAt?: string;
  user_id?: string | null;
  level_id?: string | null;
  company_id?: string;
  active?: boolean;
  type?: string | null;
  entity?: string | null;
  phone?: string | null;
  owner?: boolean;
  anonymous?: boolean;
  anonymous_name?: string | null;
  anonymous_email?: string | null;
  anonymous_avatar?: string | null;
  user?: userCreateInput;
  level?: levelCreateInput;
  company?: companyCreateInput;
  chats?: chatCreateInput[];
  kanban_templates?: kanban_templateCreateInput[];
  profile_address?: profile_addressCreateInput;
  profile_bank_accounts?: profile_bank_accountCreateInput[];
  profile_bonus?: profile_bonusCreateInput[];
  profile_contacts?: profile_contactCreateInput[];
  profile_documents?: profile_documentCreateInput[];
  profile_files?: profile_fileCreateInput[];
  profile_roles?: profile_roleCreateInput[];
  project_allocations?: project_allocationCreateInput[];
  project_kanbans?: project_kanbanCreateInput[];
  project_kanban_cycle_allocations?: project_kanban_cycle_allocationCreateInput[];
  project_kanban_cycle_cards?: project_kanban_cycle_cardCreateInput[];
  project_kanban_cycle_card_comments?: project_kanban_cycle_card_commentCreateInput[];
  project_kanban_cycle_card_reads?: project_kanban_cycle_card_readCreateInput[];
  project_members?: project_memberCreateInput[];
  project_versions?: project_versionCreateInput[];
  users_by_default_profile?: userCreateInput;
  logs?: log__profileCreateInput[];
}

export type profileUpdateInput = Partial<profileCreateInput>;

