import { subscription } from "@repo/types";

import { Pagination } from "../../../@types";

export const placeholderData: Pagination<subscription> = {
  data: [
    {
      id: "sub_placeholder_1",
      deleted: false,
      deletedAt: null,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      company_id: "company_placeholder_1",
      plan_id: "plan_placeholder_1",
      model: "standard",
      gateway_subscription_id: "gw_sub_123",
      cancel_at_period_end: false,
      canceled_at: null,
      days_off: 0,
      start_date: new Date().toISOString(),
      end_date: null,
      status: "active",
      gateway: "manual",
      is_test: false,
      cancel_in: null,
      cancel_effective_at: null,
      company: {
        id: "company_placeholder_1",
        deleted: false,
        deletedAt: null,
        language: "pt-BR",
        logo_original_name: null,
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        name: "Empresa Exemplo",
        logo: null,
        email: "empresa@exemplo.com",
        phone: "+55 11 99999-9999",
        in_config: true,
        custom: false,
        entity: "LTDA",
        type: "Tecnologia",
        creator_id: "user_creator_1",
        creator: {
          id: "user_creator_1",
          deleted: false,
          deletedAt: null,
          avatar_original_name: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          name: "João da Silva",
          avatar: null,
          provider: "email",
          email: "joao@empresa.com",
          active: true,
          password: null,
          password_confirm: null,
          need_reset: false,
          confirmed: true,
          default_profile_id: "profile_1",
          confirmed_date: new Date().toISOString(),
          recovery_code: null,
          recovery_date: null,
          confirm_code: null,
          confirm_date: null,
        },
        billing_errors: [],
        chats: [
          {
            id: "chat_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            profile_id: "profile_1",
            features: "Suporte",
            title: "Chat de Suporte",
          },
        ],
        company_address: {
          id: "address_1",
          deleted: false,
          deletedAt: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          street: "Rua Exemplo",
          complement: "Sala 101",
          city: "São Paulo",
          state: "SP",
          country: "Brasil",
          zip_code: "01000-000",
          company_id: "company_placeholder_1",
          number: "100",
          neighborhood: "Centro",
        },
        company_contacts: [
          {
            id: "contact_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            type: "comercial",
            register: "11999999999",
          },
        ],
        company_customer: {
          id: "customer_1",
          deleted: false,
          deletedAt: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          company_id: "company_placeholder_1",
          customer_id: "customer_1",
        },
        company_documents: [
          {
            id: "doc_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            type: "CNPJ",
            register: "12.345.678/0001-99",
          },
        ],
        company_files: [
          {
            id: "file_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            file: "contrato.pdf",
            vector: false,
            vector_error: null,
            name: "Contrato",
          },
        ],
        company_invoices: [
          {
            id: "invoice_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            value: 99.9,
            success: true,
            last_digits: "1234",
            metadata: null,
            flag_card: "Visa",
            currency: "BRL",
            title: "Fatura Mensal",
            status: "paga",
            description: "Assinatura mensal",
            company: undefined,
          },
        ],
        invites: [
          {
            id: "invite_1",
            deleted: false,
            deletedAt: null,
            email_send_at: null,
            expire_date: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            email: "convidado@empresa.com",
            accepted: true,
            feedback_in: null,
            level_id: "level_1",
          },
        ],
        levels: [
          {
            id: "level_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            title: "Administrador",
            active: true,
            description: "Acesso total",
            administrator: true,
          },
        ],
        modules: [
          {
            id: "module_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            title: "Gestão",
            icon: "Settings",
            integration: false,
            order: 1,
            company_id: "company_placeholder_1",
            basic: false,
          },
        ],
        notifications: [
          {
            id: "notification_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            user_id: "user_creator_1",
            company_id: "company_placeholder_1",
            read: false,
            redirect: null,
            message_key: "Bem-vindo",
            message_props: null,
            modal: null,
          },
        ],
        plans: [],
        profiles: [],
        subscriptions: [],
        subscription_changes: [],
        subscription_plans: [],
        logs: [],
      },
      plan: {
        id: "plan_placeholder_1",
        deleted: false,
        deletedAt: null,
        currency: "BRL",
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        title: "Plano Exemplo",
        price: 99.9,
        billing_model: "monthly",
        free_test: 7,
        licenses: 10,
        gateway: "manual",
        metadata: { description: "Plano para empresas de tecnologia", tags: ["premium", "mensal"] },
        price_id: "price_123",
        company_id: "company_placeholder_1",
        icon: "Award",
        is_popular: true,
        order: 1,
        company: undefined,
        plan_features: [
          {
            id: "feature_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_1",
            plan_id: "plan_placeholder_1",
            feature: {
              id: "feature_1",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "level",
              path: "user_management",
              sidebar: true,
              icon: "User",
              module_id: "module_1",
              order: 1,
              group: "admin",
              reference: "user",
              route: "/usuarios",
              show_plan: true,
              plan_title: "level",
              new: false,
              actions: "create,edit,delete",
              module: {
                id: "module_1",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Gestão",
                icon: "Settings",
                integration: false,
                order: 1,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            plan: undefined,
            plan_feature_actions: [
              {
                id: "action_1",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                plan_feature_id: "feature_1",
                action_id: "action_create",
                action: {
                  id: "action_create",
                  deleted: false,
                  integration: false,
                  deletedAt: null,
                  updatedAt: new Date().toISOString(),
                  createdAt: new Date().toISOString(),
                  title: "Criar Usuário",
                },
              },
              {
                id: "action_2",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                plan_feature_id: "feature_1",
                action_id: "action_edit",
                action: {
                  id: "action_edit",
                  deleted: false,
                  integration: false,
                  deletedAt: null,
                  updatedAt: new Date().toISOString(),
                  createdAt: new Date().toISOString(),
                  title: "Editar Usuário",
                },
              },
            ],
          },
          {
            id: "feature_2",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_2",
            plan_id: "plan_placeholder_1",
            feature: {
              id: "feature_2",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "change_logs",
              path: "reports",
              sidebar: true,
              icon: "BarChart",
              module_id: "module_2",
              order: 2,
              group: "analytics",
              reference: "report",
              route: "/relatorios",
              show_plan: true,
              plan_title: "change_logs",
              new: true,
              actions: "view,export",
              module: {
                id: "module_2",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Analytics",
                icon: "BarChart",
                integration: false,
                order: 2,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            plan: undefined,
            plan_feature_actions: [
              {
                id: "action_3",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                plan_feature_id: "feature_2",
                action_id: "action_view",
                action: {
                  id: "action_view",
                  deleted: false,
                  integration: false,
                  deletedAt: null,
                  updatedAt: new Date().toISOString(),
                  createdAt: new Date().toISOString(),
                  title: "Visualizar Relatório",
                },
              },
            ],
          },
          {
            id: "feature_3",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_3",
            plan_id: "plan_placeholder_1",
            feature: {
              id: "feature_3",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "client_file",
              path: "finance",
              sidebar: true,
              icon: "DollarSign",
              module_id: "module_3",
              order: 3,
              group: "finance",
              reference: "finance",
              route: "/financeiro",
              show_plan: true,
              plan_title: "client_file",
              new: false,
              actions: "view,export,edit",
              module: {
                id: "module_3",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Financeiro",
                icon: "DollarSign",
                integration: false,
                order: 3,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            plan: undefined,
            plan_feature_actions: [],
          },
          {
            id: "feature_4",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_4",
            plan_id: "plan_placeholder_1",
            feature: {
              id: "feature_4",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "project",
              path: "projects",
              sidebar: true,
              icon: "Folder",
              module_id: "module_4",
              order: 4,
              group: "project",
              reference: "project",
              route: "/projetos",
              show_plan: true,
              plan_title: "project",
              new: false,
              actions: "view,edit,delete",
              module: {
                id: "module_4",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Projetos",
                icon: "Folder",
                integration: false,
                order: 4,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            plan: undefined,
            plan_feature_actions: [],
          },
          {
            id: "feature_5",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_5",
            plan_id: "plan_placeholder_1",
            feature: {
              id: "feature_5",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "invite",
              path: "notifications",
              sidebar: true,
              icon: "Bell",
              module_id: "module_5",
              order: 5,
              group: "notification",
              reference: "notification",
              route: "/notificacoes",
              show_plan: true,
              plan_title: "invite",
              new: true,
              actions: "view,edit",
              module: {
                id: "module_5",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Notificações",
                icon: "Bell",
                integration: false,
                order: 5,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            plan: undefined,
            plan_feature_actions: [],
          },
        ],
        subscriptions: [
          {
            id: "sub_placeholder_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            company_id: "company_placeholder_1",
            plan_id: "plan_placeholder_1",
            model: "standard",
            gateway_subscription_id: "gw_sub_123",
            cancel_at_period_end: false,
            canceled_at: null,
            days_off: 0,
            start_date: new Date().toISOString(),
            end_date: null,
            status: "active",
            gateway: "manual",
            is_test: false,
            cancel_in: null,
            cancel_effective_at: null,
          },
        ],
        subscription_changes: [
          {
            id: "change_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            subscription_id: "sub_placeholder_1",
            from_plan_id: "plan_placeholder_0",
            to_plan_id: "plan_placeholder_1",
            change_type: "upgrade",
            effective_date: new Date().toISOString(),
            metadata: { motivo: "Crescimento da empresa" },
            company_id: "company_placeholder_1",
          },
        ],
        subscription_changes_by_to_plan: [],
      },
      subscription_changes: [
        {
          id: "change_1",
          deleted: false,
          deletedAt: null,
          updatedAt: new Date().toISOString(),
          createdAt: new Date().toISOString(),
          subscription_id: "sub_placeholder_1",
          from_plan_id: "plan_placeholder_0",
          to_plan_id: "plan_placeholder_1",
          change_type: "upgrade",
          effective_date: new Date().toISOString(),
          metadata: { motivo: "Crescimento da empresa" },
          company_id: "company_placeholder_1",
        },
      ],
      subscription_plan: {
        id: "subplan_1",
        deleted: false,
        deletedAt: null,
        updatedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        subscription_id: "sub_placeholder_1",
        currency: "BRL",
        title: "Plano Exemplo",
        price: 99.9,
        billing_model: "monthly",
        free_test: 7,
        licenses: 10,
        gateway: "manual",
        company_id: "company_placeholder_1",
        icon: "Award",
        metadata: { description: "Plano de assinatura ativo", tags: ["ativo", "mensal"] },
        price_id: "price_123",
        subscription: undefined,
        company: undefined,
        subscription_plan_features: [
          {
            id: "spf_1",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_1",
            subscription_plan_id: "subplan_1",
            feature: {
              id: "feature_1",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "level",
              path: "user_management",
              sidebar: true,
              icon: "User",
              module_id: "module_1",
              order: 1,
              group: "admin",
              reference: "user",
              route: "/usuarios",
              show_plan: true,
              plan_title: "level",
              new: false,
              actions: "create,edit,delete",
              module: {
                id: "module_1",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Gestão",
                icon: "Settings",
                integration: false,
                order: 1,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            subscription_plan: undefined,
            subscription_plan_feature_actions: [],
          },
          {
            id: "spf_2",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_2",
            subscription_plan_id: "subplan_1",
            feature: {
              id: "feature_2",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "change_logs",
              path: "reports",
              sidebar: true,
              icon: "BarChart",
              module_id: "module_2",
              order: 2,
              group: "analytics",
              reference: "report",
              route: "/relatorios",
              show_plan: true,
              plan_title: "change_logs",
              new: true,
              actions: "view,export",
              module: {
                id: "module_2",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Analytics",
                icon: "BarChart",
                integration: false,
                order: 2,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            subscription_plan: undefined,
            subscription_plan_feature_actions: [],
          },
          {
            id: "spf_3",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_3",
            subscription_plan_id: "subplan_1",
            feature: {
              id: "feature_3",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "client_file",
              path: "finance",
              sidebar: true,
              icon: "DollarSign",
              module_id: "module_3",
              order: 3,
              group: "finance",
              reference: "finance",
              route: "/financeiro",
              show_plan: true,
              plan_title: "client_file",
              new: false,
              actions: "view,export,edit",
              module: {
                id: "module_3",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Financeiro",
                icon: "DollarSign",
                integration: false,
                order: 3,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            subscription_plan: undefined,
            subscription_plan_feature_actions: [],
          },
          {
            id: "spf_4",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_4",
            subscription_plan_id: "subplan_1",
            feature: {
              id: "feature_4",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "project",
              path: "projects",
              sidebar: true,
              icon: "Folder",
              module_id: "module_4",
              order: 4,
              group: "project",
              reference: "project",
              route: "/projetos",
              show_plan: true,
              plan_title: "project",
              new: false,
              actions: "view,edit,delete",
              module: {
                id: "module_4",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Projetos",
                icon: "Folder",
                integration: false,
                order: 4,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            subscription_plan: undefined,
            subscription_plan_feature_actions: [],
          },
          {
            id: "spf_5",
            deleted: false,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            feature_id: "feature_5",
            subscription_plan_id: "subplan_1",
            feature: {
              id: "feature_5",
              deleted: false,
              deletedAt: null,
              updatedAt: new Date().toISOString(),
              createdAt: new Date().toISOString(),
              title: "invite",
              path: "notifications",
              sidebar: true,
              icon: "Bell",
              module_id: "module_5",
              order: 5,
              group: "notification",
              reference: "notification",
              route: "/notificacoes",
              show_plan: true,
              plan_title: "invite",
              new: true,
              actions: "view,edit",
              module: {
                id: "module_5",
                deleted: false,
                deletedAt: null,
                updatedAt: new Date().toISOString(),
                createdAt: new Date().toISOString(),
                title: "Notificações",
                icon: "Bell",
                integration: false,
                order: 5,
                company_id: "company_placeholder_1",
                basic: false,
              },
            },
            subscription_plan: undefined,
            subscription_plan_feature_actions: [],
          },
        ],
      },
    },
  ],
  count: 1,
  page: 1,
  pages: 1,
};
